# Mesh Metadata Notebook
All activations for `metadata_utils.py`.  
Run cells top-to-bottom. Edit the **CONFIG** cell to point at your files.

## 1 · Imports

In [1]:
import sys
import pandas as pd

# Point this to wherever metadata_utils.py lives
sys.path.insert(0, ".")          # same folder as this notebook
from meta_utils import *

## 2 · Config  ← edit here

In [2]:
# ── paths ─────────────────────────────────────────────────────────────────────
INPUT_FILE  = "mesh_metadata_2026-01-07.csv"
OUTPUT_CSV  = "links_metadata_output.csv"
OUTPUT_JSON = "links_mapping.json"

# ── grouping ──────────────────────────────────────────────────────────────────
SAME_LOC_M  = 10.0      # metres: two endpoints considered the same location

# ── filters ───────────────────────────────────────────────────────────────────
MIN_LENGTH_M = 10.0     # drop sublinks shorter than this  (0 = keep all)
MIN_FREQ_MHZ = 0.0      # drop sublinks below this freq    (0 = keep all)

DROP_CML_IF_ALL_LENGTH_MISSING = False   # True = drop entire CML if all sublinks have no length
DROP_CML_IF_ALL_FREQ_MISSING   = False   # True = drop entire CML if all sublinks have no freq

# ── bounding box (NYC defaults) ───────────────────────────────────────────────
LAT_MIN, LAT_MAX =  40.4,  41.0
LON_MIN, LON_MAX = -74.4, -73.5

## 3 · Run full pipeline

In [3]:
links_df, mapping = run_pipeline(
    input_path                    = INPUT_FILE,
    output_csv                    = OUTPUT_CSV,
    output_json                   = OUTPUT_JSON,
    same_loc_m                    = SAME_LOC_M,
    min_length_m                  = MIN_LENGTH_M,
    min_freq_mhz                  = MIN_FREQ_MHZ,
    drop_cml_if_all_length_missing = DROP_CML_IF_ALL_LENGTH_MISSING,
    drop_cml_if_all_freq_missing   = DROP_CML_IF_ALL_FREQ_MISSING,
    lat_min=LAT_MIN, lat_max=LAT_MAX,
    lon_min=LON_MIN, lon_max=LON_MAX,
)
links_df.head(10)

Loading      : mesh_metadata_2026-01-07.csv
  [coord fix] flipped sign on 3 longitude value(s)
  Source rows: 1989
Grouping     (same-location threshold = 10.0 m) ...
  Raw groups : 440
Converting   (length >= 10.0 m, freq >= 0.0 MHz) ...
  CMLs       : 271
  Sublinks   : 333
Saved CSV    : links_metadata_output.csv
Saved JSON   : links_mapping.json

,cml_id,sublink_id,device_name,site_0_lat,site_0_lon,site_0_elevation,site_0_altitude,site_1_lat,site_1_lon,site_1_elevation,site_1_altitude,frequency,frequency_units,length,polarization,tsl,rsl
0,1,sublink_1,nycmesh-5916-wavepro-3461 <-> nycmesh-3461-wav...,40.696031,-73.939812,NaN,97.8,40.672610,-73.963951,NaN,115.4,69120.0,MHz,3327.000000,ap-ptp,-43.0,-43.0
1,2,sublink_1,nycmesh-730-wavepro-2299 <-> nycmesh-2299-wave...,40.843925,-73.893033,NaN,72.0,40.861363,-73.907873,NaN,80.4,69120.0,MHz,2224.000000,ap-ptp,-43.0,-42.0
2,3,sublink_1,nycmesh-1933-wavenano <-> nycmesh-227-waveapmi...,40.715550,-73.984461,NaN,110.2,40.711199,-74.001357,10.0,189.9,69120.0,MHz,1503.999265,sta-ptmp,-63.0,-61.0
3,4,sublink_1,nycmesh-227-waveapmicro-north <-> nycmesh-168-...,40.711199,-74.001357,10.0,189.9,40.709724,-73.958190,NaN,29.4,69120.0,MHz,3640.000000,ap-ptmp,-59.0,-61.0
4,5,sublink_1,nycmesh-227-waveapmicro-north <-> nycmesh-544-...,40.711199,-74.001357,10.0,189.9,40.718492,-73.996155,NaN,37.5,69120.0,MHz,955.000000,ap-ptmp,-59.0,-57.0
5,6,sublink_1,nycmesh-1933-netpower16p <-> nycmesh-1933-af60...,40.715467,-73.984401,NaN,97.0,40.715632,-73.984391,NaN,91.0,NaN,MHz,18.366511,ap-ptp,-67.0,-64.0
6,6,sublink_2,nycmesh-1933-netpower16p <-> nycmesh-1933-af60...,40.715467,-73.984401,NaN,97.0,40.715592,-73.984405,NaN,98.3,NaN,MHz,13.903454,ap-ptmp,-63.0,-63.0
7,6,sublink_3,nycmesh-1933-netpower16p <-> nycmesh-1933-af60...,40.715467,-73.984401,NaN,97.0,40.715592,-73.984427,NaN,97.0,NaN,MHz,14.071041,ap-ptmp-airmax-mixed,-75.0,-74.0
8,6,sublink_4,nycmesh-1933-netpower16p <-> nycmesh-1933-af60...,40.715648,-73.984369,NaN,107.1,40.715467,-73.984401,NaN,0.0,69120.0,MHz,20.292927,ap-ptmp,-62.0,-63.0
9,6,sublink_5,nycmesh-1933-netpower16p <-> nycmesh-1933-af60...,40.715467,-73.984401,NaN,97.0,40.715648,-73.984369,NaN,107.1,NaN,MHz,20.306181,ap-ptmp,-62.0,-61.0

## 4 · Inspect output

In [4]:
print(f"CMLs     : {links_df['cml_id'].nunique()}")
print(f"Sublinks : {len(links_df)}")
print(f"Columns  : {list(links_df.columns)}")
links_df.head()

CMLs     : 271
Sublinks : 333
Columns  : ['cml_id', 'sublink_id', 'device_name', 'site_0_lat', 'site_0_lon', 'site_0_elevation', 'site_0_altitude', 'site_1_lat', 'site_1_lon', 'site_1_elevation', 'site_1_altitude', 'frequency', 'frequency_units', 'length', 'polarization', 'tsl', 'rsl']

,cml_id,sublink_id,device_name,site_0_lat,site_0_lon,site_0_elevation,site_0_altitude,site_1_lat,site_1_lon,site_1_elevation,site_1_altitude,frequency,frequency_units,length,polarization,tsl,rsl
0,1,sublink_1,nycmesh-5916-wavepro-3461 <-> nycmesh-3461-wav...,40.696031,-73.939812,NaN,97.8,40.672610,-73.963951,NaN,115.4,69120.0,MHz,3327.000000,ap-ptp,-43.0,-43.0
1,2,sublink_1,nycmesh-730-wavepro-2299 <-> nycmesh-2299-wave...,40.843925,-73.893033,NaN,72.0,40.861363,-73.907873,NaN,80.4,69120.0,MHz,2224.000000,ap-ptp,-43.0,-42.0
2,3,sublink_1,nycmesh-1933-wavenano <-> nycmesh-227-waveapmi...,40.715550,-73.984461,NaN,110.2,40.711199,-74.001357,10.0,189.9,69120.0,MHz,1503.999265,sta-ptmp,-63.0,-61.0
3,4,sublink_1,nycmesh-227-waveapmicro-north <-> nycmesh-168-...,40.711199,-74.001357,10.0,189.9,40.709724,-73.958190,NaN,29.4,69120.0,MHz,3640.000000,ap-ptmp,-59.0,-61.0
4,5,sublink_1,nycmesh-227-waveapmicro-north <-> nycmesh-544-...,40.711199,-74.001357,10.0,189.9,40.718492,-73.996155,NaN,37.5,69120.0,MHz,955.000000,ap-ptmp,-59.0,-57.0

## 5 · Load saved CSV (skip pipeline re-run)

In [5]:
# Use this cell if you already have the output CSV and just want to query it
links_df = pd.read_csv(OUTPUT_CSV)
print(f"Loaded {len(links_df)} rows, {links_df['cml_id'].nunique()} CMLs")
links_df.head()

Loaded 333 rows, 271 CMLs

,cml_id,sublink_id,device_name,site_0_lat,site_0_lon,site_0_elevation,site_0_altitude,site_1_lat,site_1_lon,site_1_elevation,site_1_altitude,frequency,frequency_units,length,polarization,tsl,rsl
0,1,sublink_1,nycmesh-5916-wavepro-3461 <-> nycmesh-3461-wav...,40.696031,-73.939812,NaN,97.8,40.672610,-73.963951,NaN,115.4,69120.0,MHz,3327.000000,ap-ptp,-43.0,-43.0
1,2,sublink_1,nycmesh-730-wavepro-2299 <-> nycmesh-2299-wave...,40.843925,-73.893033,NaN,72.0,40.861363,-73.907873,NaN,80.4,69120.0,MHz,2224.000000,ap-ptp,-43.0,-42.0
2,3,sublink_1,nycmesh-1933-wavenano <-> nycmesh-227-waveapmi...,40.715550,-73.984461,NaN,110.2,40.711199,-74.001357,10.0,189.9,69120.0,MHz,1503.999265,sta-ptmp,-63.0,-61.0
3,4,sublink_1,nycmesh-227-waveapmicro-north <-> nycmesh-168-...,40.711199,-74.001357,10.0,189.9,40.709724,-73.958190,NaN,29.4,69120.0,MHz,3640.000000,ap-ptmp,-59.0,-61.0
4,5,sublink_1,nycmesh-227-waveapmicro-north <-> nycmesh-544-...,40.711199,-74.001357,10.0,189.9,40.718492,-73.996155,NaN,37.5,69120.0,MHz,955.000000,ap-ptmp,-59.0,-57.0

## 6 · Lookup by coordinates
Returns all raw rows whose site endpoint is within `radius_m` metres of the query point.  
`site` options: `"any"` (default) | `"site_0"` | `"site_1"`

In [6]:
# ── edit these ────────────────────────────────────────────────────────────────
QUERY_LAT  = 40.696
QUERY_LON  = -73.940
RADIUS_M   = 50.0
SITE       = "any"       # "any" | "site_0" | "site_1"
# ──────────────────────────────────────────────────────────────────────────────

results = lookup_by_coords(links_df, lat=QUERY_LAT, lon=QUERY_LON,
                           radius_m=RADIUS_M, site=SITE)

print(f"Found {len(results)} matching row(s)")
results

Found 44 matching row(s)

,cml_id,sublink_id,device_name,site_0_lat,site_0_lon,site_0_elevation,site_0_altitude,site_1_lat,site_1_lon,site_1_elevation,site_1_altitude,frequency,frequency_units,length,polarization,tsl,rsl,matched_site,distance_m
0,88,sublink_1,nycmesh-5916-west1 <-> nycmesh-lbelr2-854,40.696017,-73.939873,NaN,67.46,40.711568,-73.946966,NaN,10.00,5710.0,MHz,1830.000000,ap-ptmp-airmax-mixed,-76.0,-69.0,site_0,10.87
1,1,sublink_1,nycmesh-5916-wavepro-3461 <-> nycmesh-3461-wav...,40.696031,-73.939812,NaN,97.80,40.672610,-73.963951,NaN,115.40,69120.0,MHz,3327.000000,ap-ptp,-43.0,-43.0,site_0,16.22
2,220,sublink_1,nycmesh-lbe-436 <-> nycmesh-436-omni,40.696000,-73.939800,23.0,15.00,40.685934,-73.961314,NaN,15.00,NaN,MHz,2131.432956,sta-ptmp,-73.0,-65.0,site_0,16.86
3,213,sublink_1,nycmesh-lbe-4126 <-> nycmesh-4126-np16,40.696000,-73.939800,23.0,10.00,40.692245,-73.954483,NaN,10.00,NaN,MHz,1306.416576,sta-ptmp,-67.0,-60.0,site_0,16.86
4,138,sublink_1,nycmesh-5916-lbe-west <-> nycmesh-lbe-430,40.696000,-73.939800,NaN,67.46,40.694920,-73.949380,23.0,16.00,5490.0,MHz,821.000000,ap-ptmp-airmax-mixed,-57.0,-56.0,site_0,16.86
5,139,sublink_1,nycmesh-5916-lbe-west <-> nycmesh-lbe-1779,40.696000,-73.939800,NaN,67.46,40.694000,-73.955000,23.0,25.00,5490.0,MHz,1286.000000,ap-ptmp-airmax-mixed,-58.0,-60.0,site_0,16.86
6,103,sublink_1,nycmesh-3461-northeast <-> nycmesh-lbelr-219,40.672685,-73.963860,NaN,60.95,40.696000,-73.939800,NaN,10.00,5560.0,MHz,2027.000000,ap-ptmp-airmax-mixed,-68.0,-66.0,site_1,16.86
7,205,sublink_1,nycmesh-219-netpower16p <-> nycmesh-lbelr-219,40.674366,-73.940284,NaN,10.00,40.696000,-73.939800,NaN,10.00,NaN,MHz,2027.000000,sta-ptmp,-68.0,-66.0,site_1,16.86
8,71,sublink_1,nycmesh-2482-nbe-6248 <-> nycmesh-6248-lbe-2482,40.699700,-73.924300,23.0,10.00,40.696000,-73.939800,23.0,5.00,5770.0,MHz,1369.941562,ap-ptp,-45.0,-45.0,site_1,16.86
9,82,sublink_1,nycmesh-1340-north2 <-> nycmesh-lbe-254,40.685988,-73.917573,NaN,12.93,40.696000,-73.939800,23.0,5.00,5745.0,MHz,2210.000000,ap-ptmp-airmax-mixed,-44.0,-61.0,site_1,16.86
10,131,sublink_1,nycmesh-5916-south1 <-> nycmesh-lbe-158,40.696042,-73.939797,NaN,67.46,40.691635,-73.924396,23.0,10.00,5490.0,MHz,1382.000000,ap-ptmp-airmax-mixed,-63.0,-59.0,site_0,17.74
11,23,sublink_1,nycmesh-5916-waveap-south <-> nycmesh-155-af60lr,40.696113,-73.939843,NaN,90.00,40.679826,-73.942373,18.0,50.10,66960.0,MHz,1811.000000,ap-ptmp,-59.0,-55.0,site_0,18.25
12,176,sublink_1,nycmesh-5916-core <-> nycmesh-5916-waveap-south,40.696038,-73.939764,NaN,67.46,40.696113,-73.939843,NaN,90.00,NaN,MHz,10.672713,ap-ptmp,-59.0,-57.0,both,18.25
13,31,sublink_1,nycmesh-5916-waveap-south <-> nycmesh-3607-af60lr,40.696113,-73.939843,NaN,90.00,40.682834,-73.945901,NaN,33.20,66960.0,MHz,1563.000000,ap-ptmp,-59.0,-53.0,site_0,18.25
14,26,sublink_1,nycmesh-5916-waveap-south <-> nycmesh-219-af60lr,40.696113,-73.939843,NaN,90.00,40.674366,-73.940325,23.0,48.60,66960.0,MHz,2410.000000,ap-ptmp,-59.0,-56.0,site_0,18.25
15,115,sublink_1,nycmesh-5916-south2 <-> nycmesh-lbe-3607,40.696048,-73.939788,NaN,67.46,40.683000,-73.946000,23.0,10.00,5550.0,MHz,1563.000000,ap-ptmp-airmax-mixed,-65.0,-58.0,site_0,18.65
16,114,sublink_1,nycmesh-5916-south2 <-> nycmesh-lbe-7325,40.696048,-73.939788,NaN,67.46,40.689000,-73.952000,23.0,5.00,5550.0,MHz,1310.000000,ap-ptmp-airmax-mixed,-63.0,-56.0,site_0,18.65
17,113,sublink_1,nycmesh-5916-south2 <-> nycmesh-lbe-1350,40.696048,-73.939788,NaN,67.46,40.687437,-73.947464,NaN,30.00,5550.0,MHz,1156.000000,ap-ptmp-airmax-mixed,-62.0,-56.0,site_0,18.65
18,189,sublink_1,nycmesh-5916-eps16 <-> nycmesh-5916-gbelr-265,40.696038,-73.939764,23.0,67.46,40.696280,-73.939760,NaN,0.00,NaN,MHz,26.911285,ap-ptp,-62.0,-60.0,both,20.34
19,202,sublink_1,nycmesh-5916-netpower16p <-> nycmesh-5916-af60...,40.696038,-73.939764,NaN,67.46,40.695935,-73.939753,23.0,98.40,NaN,MHz,2210.000000,sta-ptp,-58.0,-55.0,both,20.34
20,210,sublink_1,nycmesh-5916-netpower16p <-> nycmesh-5916-wave...,40.696038,-73.939764,NaN,67.46,40.696153,-73.939618,NaN,95.10,NaN,MHz,17.748809,ap-ptmp,-60.0,-56.0,both,20.34
21,210,sublink_2,nycmesh-5916-netpower16p <-> nycmesh-5916-wave...,40.696038,-73.939764,NaN,67.46,40.696125,-73.939608,NaN,91.00,NaN,MHz,16.326426,ap-ptmp,-56.0,-60.0,both,20.34
22,212,sublink_1,nycmesh-5916-eh8010-162 <-> nycmesh-162-eh8010...,40.696038,-73.939764,NaN,67.46,40.664997,-73.990543,NaN,40.00,NaN,MHz,5499.882242,NaN,NaN,NaN,site_0,20.34
23,197,sublink_1,nycmesh-5916-netpower16p <-> nycmesh-5916-wave...,40.696038,-73.939764,NaN,67.46,40.696036,-73.939630,NaN,99.90,NaN,MHz,11.299153,ap-ptmp,-59.0,-58.0,both,20.34
24,103,sublink_3,nycmesh-3461-northeast <-> nycmesh-lbelr-219,40.672685,-73.963860,NaN,60.95,40.696038,-73.939764,23.0,5.00,5510.0,MHz,3327.000000,ap-ptmp,-67.0,-73.0,site_1,20.34
25,243,sublink_1,nycmesh-1933-eh8010-5916 <-> nycmesh-5916-eh80...,40.715467,-73.984401,NaN,97.00,40.696038,-73.939764,NaN,67.46,NaN,MHz,4338.726861,NaN,NaN,NaN,site_1,20.34
26,237,sublink_1,nycmesh-5916-force6g-835 <-> nycmesh-835-force...,40.696038,-73.939764,NaN,67.46,40.685214,-73.954595,NaN,10.00,NaN,MHz,1735.565900,NaN,NaN,NaN,site_0,20.34
27,82,sublink_2,nycmesh-1340-north2 <-> nycmesh-lbe-254,40.685988,-73.917573,NaN,12.93,40.696038,-73.939764,23.0,5.00,5745.0,MHz,2210.000000,ap-ptmp-airmax-mixed,-44.0,-52.0,site_1,20.34
28,71,sublink_2,nycmesh-2482-nbe-6248 <-> nycmesh-6248-lbe-2482,40.696038,-73.939764,NaN,67.46,40.699705,-73.924278,23.0,10.00,5550.0,MHz,1367.000000,ap-ptmp-airmax-mixed,-61.0,-65.0,site_0,20.34
29,103,sublink_2,nycmesh-3461-northeast <-> nycmesh-lbelr-219,40.672685,-73.963860,NaN,60.95,40.696038,-73.939764,23.0,5.00,5560.0,MHz,3327.000000,ap-ptmp-airmax-mixed,-69.0,-68.0,site_1,20.34
30,35,sublink_1,nycmesh-5916-af60lr-1340 <-> nycmesh-1340-af60...,40.695935,-73.939753,23.0,98.40,40.686118,-73.917444,NaN,68.00,65880.0,MHz,2174.728099,sta-ptp,-58.0,-58.0,site_0,22.04
31,97,sublink_1,nycmesh-5916-east1 <-> nycmesh-lbe-875,40.696070,-73.939677,NaN,67.46,40.672531,-73.964197,NaN,5.00,5710.0,MHz,3327.000000,ap-ptmp-airmax-mixed,-58.0,-56.0,site_0,28.32
32,19,sublink_1,nycmesh-5916-east1 <-> nycmesh-lbe-921,40.696070,-73.939677,NaN,67.46,40.714537,-73.914361,NaN,10.00,5710.0,MHz,3659.000000,ap-ptmp-airmax-mixed,-72.0,-72.0,site_0,28.32
33,94,sublink_1,nycmesh-5916-east1 <-> nycmesh-lbelr-265,40.696070,-73.939677,NaN,67.46,40.705347,-73.930856,NaN,24.00,5710.0,MHz,1265.000000,ap-ptmp-airmax-mixed,-64.0,-64.0,site_0,28.32
34,19,sublink_2,nycmesh-5916-east1 <-> nycmesh-lbe-921,40.696036,-73.939630,NaN,99.90,40.714514,-73.914362,NaN,23.40,68040.0,MHz,3659.000000,ap-ptmp,-59.0,-57.0,site_0,31.45
35,16,sublink_1,nycmesh-5916-waveap-northeast <-> nycmesh-664-...,40.696036,-73.939630,NaN,99.90,40.705677,-73.915254,NaN,39.20,68040.0,MHz,2326.000000,ap-ptmp,-59.0,-66.0,site_0,31.45
36,12,sublink_1,nycmesh-5916-waveap-northeast <-> nycmesh-2482...,40.696036,-73.939630,NaN,99.90,40.699694,-73.924387,NaN,34.00,68040.0,MHz,1367.000000,ap-ptmp,-59.0,-58.0,site_0,31.45
37,9,sublink_1,nycmesh-5916-waveap-northeast <-> nycmesh-169-...,40.696036,-73.939630,NaN,99.90,40.708580,-73.921552,8.0,24.20,68040.0,MHz,2043.000000,ap-ptmp,-59.0,-58.0,site_0,31.45
38,40,sublink_1,nycmesh-5916-waveapmicro-southeast <-> nycmesh...,40.696125,-73.939608,NaN,91.00,40.691716,-73.924483,23.0,38.70,64800.0,MHz,1382.000000,ap-ptmp,-56.0,-56.0,site_0,35.85
39,29,sublink_1,nycmesh-5916-waveap-west <-> nycmesh-1779-af60lr,40.696153,-73.939618,NaN,95.10,40.694040,-73.954797,23.0,0.00,66960.0,MHz,1286.000000,ap-ptmp,-60.0,-54.0,site_0,36.42
40,24,sublink_1,nycmesh-5916-waveap-west <-> nycmesh-4126-af60lr,40.696153,-73.939618,NaN,95.10,40.692256,-73.954504,NaN,51.30,66960.0,MHz,1310.000000,ap-ptmp,-60.0,-52.0,site_0,36.42
41,34,sublink_1,nycmesh-5916-waveap-west <-> nycmesh-436-af60lr,40.696153,-73.939618,NaN,95.10,40.685986,-73.961279,23.0,41.30,66960.0,MHz,2136.000000,ap-ptmp,-60.0,-70.0,site_0,36.42
42,32,sublink_1,nycmesh-5916-waveap-west <-> ncymesh-430-af60lr,40.696153,-73.939618,NaN,95.10,40.694918,-73.949413,23.0,33.80,66960.0,MHz,821.000000,ap-ptmp,-60.0,-55.0,site_0,36.42
43,48,sublink_1,nycmesh-5916-gbelr-265 <-> nycmesh-265-gbelr-5916,40.696280,-73.939760,NaN,0.00,40.705214,-73.930748,NaN,0.00,60480.0,MHz,1265.000000,ap-ptp,-62.0,-63.0,site_0,37.13

## 7 · Get elevation at coordinates

In [7]:
results = lookup_by_coords(links_df, lat=QUERY_LAT, lon=QUERY_LON, radius_m=RADIUS_M)

elev_cols = ["cml_id", "device_name", "matched_site", "distance_m",
             "site_0_elevation", "site_0_altitude",
             "site_1_elevation", "site_1_altitude"]

results[elev_cols].head(10)

,cml_id,device_name,matched_site,distance_m,site_0_elevation,site_0_altitude,site_1_elevation,site_1_altitude
0,88,nycmesh-5916-west1 <-> nycmesh-lbelr2-854,site_0,10.87,NaN,67.46,NaN,10.0
1,1,nycmesh-5916-wavepro-3461 <-> nycmesh-3461-wav...,site_0,16.22,NaN,97.80,NaN,115.4
2,220,nycmesh-lbe-436 <-> nycmesh-436-omni,site_0,16.86,23.0,15.00,NaN,15.0
3,213,nycmesh-lbe-4126 <-> nycmesh-4126-np16,site_0,16.86,23.0,10.00,NaN,10.0
4,138,nycmesh-5916-lbe-west <-> nycmesh-lbe-430,site_0,16.86,NaN,67.46,23.0,16.0
5,139,nycmesh-5916-lbe-west <-> nycmesh-lbe-1779,site_0,16.86,NaN,67.46,23.0,25.0
6,103,nycmesh-3461-northeast <-> nycmesh-lbelr-219,site_1,16.86,NaN,60.95,NaN,10.0
7,205,nycmesh-219-netpower16p <-> nycmesh-lbelr-219,site_1,16.86,NaN,10.00,NaN,10.0
8,71,nycmesh-2482-nbe-6248 <-> nycmesh-6248-lbe-2482,site_1,16.86,23.0,10.00,23.0,5.0
9,82,nycmesh-1340-north2 <-> nycmesh-lbe-254,site_1,16.86,NaN,12.93,23.0,5.0

## 8 · Step-by-step pipeline  *(optional — run_pipeline does all of this)*
Useful if you want to inspect intermediate outputs.

In [8]:
# Step 1: load & fix coords
raw_df = load_mesh(INPUT_FILE, LAT_MIN, LAT_MAX, LON_MIN, LON_MAX)
print(f"Loaded {len(raw_df)} valid rows")
raw_df.head(3)

  [coord fix] flipped sign on 3 longitude value(s)
Loaded 1989 valid rows

,time,cml_id,sublink_id,tx_id,tx_name,rx_id,rx_name,site_0_lat,site_0_lon,site_0_elevation,...,site_1_lat,site_1_lon,site_1_elevation,site_1_altitude,length,frequency,frequency_units,tsl,rsl,polarization
0,2026-01-07T19:37:44,a57ddde1-6fff-463a-bbee-cbe90258daa6_c73f546c-...,00019977-29f9-35eb-b4b2-5e37f0a73cf1,a57ddde1-6fff-463a-bbee-cbe90258daa6,nycmesh-1932-olt-410,c73f546c-18ba-4e5f-8cc4-86542ad7dd9a,410-21E,40.716098,-73.985997,14.0,...,40.716338,-73.986263,14.0,5.0,34.853616,NaN,NaN,4.0,-18.0,NaN
1,2026-01-07T19:37:44,4a6f43ed-ac8b-41c6-867b-e893d9737c31_cb7be75d-...,002a7874-1273-36d9-81d5-a8173f18f3d0,4a6f43ed-ac8b-41c6-867b-e893d9737c31,nycmesh-1936-olt-xgs-165,cb7be75d-ee3a-4ed9-a945-c0dfeda99bc4,1936-09M,40.716797,-73.985577,NaN,...,40.716797,-73.985577,NaN,5.0,0.000000,NaN,NaN,4.0,-17.0,NaN
2,2026-01-07T19:37:44,9e2a74d5-e888-4817-9c41-e8dfb830e11d_50e0abe2-...,002b1d2f-3ae7-3063-96f8-f65c05a39494,9e2a74d5-e888-4817-9c41-e8dfb830e11d,nycmesh-5916-waveap-west,50e0abe2-d07f-4ccc-a395-0884c89bee43,ncymesh-430-af60lr,40.696153,-73.939618,NaN,...,40.694918,-73.949413,23.0,33.8,821.000000,66960.0,MHz,-60.0,-55.0,ap-ptmp

In [9]:
# Step 2: group into CMLs
groups = build_groups(raw_df, thr=SAME_LOC_M)
print(f"Groups formed: {len(groups)}")

Groups formed: 440

In [10]:
# Step 3: convert
links_df2, mapping2 = convert(
    raw_df, groups,
    min_length_m                  = MIN_LENGTH_M,
    min_freq_mhz                  = MIN_FREQ_MHZ,
    drop_cml_if_all_length_missing = DROP_CML_IF_ALL_LENGTH_MISSING,
    drop_cml_if_all_freq_missing   = DROP_CML_IF_ALL_FREQ_MISSING,
)
print(f"CMLs: {links_df2['cml_id'].nunique()}  |  Sublinks: {len(links_df2)}")
links_df2.head()

CMLs: 271  |  Sublinks: 333

,cml_id,sublink_id,device_name,site_0_lat,site_0_lon,site_0_elevation,site_0_altitude,site_1_lat,site_1_lon,site_1_elevation,site_1_altitude,frequency,frequency_units,length,polarization,tsl,rsl
0,1,sublink_1,nycmesh-1932-olt-410 <-> 410-21E,40.716098,-73.985997,14.0,100.32,40.716338,-73.986263,14.0,5.00,NaN,MHz,34.853616,None,4.0,-18.0
1,2,sublink_1,nycmesh-5916-waveap-west <-> ncymesh-430-af60lr,40.696153,-73.939618,NaN,95.10,40.694918,-73.949413,23.0,33.80,66960.0,MHz,821.000000,ap-ptmp,-60.0,-55.0
2,3,sublink_1,nycmesh-2282-eps16 <-> nycmesh-2282-southeast,40.682995,-73.993789,13.0,18.29,40.682896,-73.993683,13.0,18.29,NaN,MHz,14.180033,ap-ptmp-airmax-mixed,-58.0,-55.0
3,4,sublink_1,nycmesh-1340-eps16 <-> nycmesh-1340-east,40.685823,-73.917272,NaN,12.93,40.686016,-73.917493,NaN,53.30,NaN,MHz,28.421801,ap-ptmp-airmax-mixed,NaN,NaN
4,4,sublink_2,nycmesh-1340-eps16 <-> nycmesh-1340-east,40.685823,-73.917272,NaN,12.93,40.686016,-73.917493,NaN,53.30,NaN,MHz,28.421801,ap-ptp,-66.0,-62.0

,cml_id,sublink_id,device_name,site_0_lat,site_0_lon,site_0_elevation,site_0_altitude,site_1_lat,site_1_lon,site_1_elevation,...,frequency,frequency_units,length,polarization,tsl,rsl,matched_site_a,distance_a_m,matched_site_b,distance_b_m
0,44,sublink_1,nycmesh-2463-gbep-2274 <-> nycmesh-2274-gbep-2463,40.720668,-73.988049,11.0,0.0,40.725903,-73.983635,NaN,...,62640.0,MHz,744.0,ap-ptp,-61.0,-59.0,site_0,0.0,site_1,0.0

## 9 · Inspect mapping dict

In [ ]:
import json

# Show full mapping entry for a specific cml_id
CML_ID = 1

entry = mapping.get(CML_ID)
if entry:
    print(json.dumps(entry, indent=2, default=str))
else:
    print(f"cml_id {CML_ID} not found")

## 10 · Filter by any field(s)

In [ ]:
from metadata_utils import filter_by_fields

# ── single field, exact value ─────────────────────────────────────────────────
filter_by_fields(links_df, {"polarization": "v"})

In [ ]:
# ── single field, list of accepted values ────────────────────────────────────
filter_by_fields(links_df, {"polarization": ["v", "h"]})

In [ ]:
# ── single field, callable (lambda for ranges / custom logic) ─────────────────
filter_by_fields(links_df, {"frequency": lambda f: f is not None and f >= 5000})

In [ ]:
# ── tuple of columns that must match together ─────────────────────────────────
filter_by_fields(links_df, {("site_0_lat", "site_0_lon"): (40.696153, -73.939618)})

In [ ]:
# ── multiple filters combined (AND logic) ────────────────────────────────────
filter_by_fields(links_df, {
    "polarization" : ["v", "h"],
    "frequency"    : lambda f: f is not None and f >= 5000,
})

## 11 · Get elevation from df by coordinates

In [ ]:
from metadata_utils import get_elevation_from_df

coords = [
    (40.720668, -73.988049),   # site A
    (40.725903, -73.983635),   # site B
]

result = get_elevation_from_df(links_df, coords, radius_m=50)
result

In [ ]:
# Just the elevation column
result[["query_lat", "query_lon", "device_name", "matched_site", "distance_m", "elevation"]]

## 12 · Find links by coordinates

In [ ]:
from metadata_utils import find_link

# ── all links touching one site ───────────────────────────────────────────────
r = find_link(links_df, site_a=(40.720668, -73.988049))
r[["cml_id", "device_name", "sublink_id", "matched_site_a", "distance_a_m"]]

In [ ]:
# ── the specific link between two sites (direction-agnostic) ─────────────────
r = find_link(links_df,
              site_a=(40.720668, -73.988049),
              site_b=(40.725903, -73.983635))
r

In [ ]:
# ── tighter radius if too many results ───────────────────────────────────────
r = find_link(links_df, site_a=(40.720668, -73.988049), radius_m=10)
r[["cml_id", "device_name", "matched_site_a", "distance_a_m"]]

In [ ]:
from metadata_utils import find_link

# CML ID 16 from OpenMesh — site A & site B coordinates
r = find_link(links_df,
              site_a=(40.720668, -73.988049),
              site_b=(40.725903, -73.983635))
r